[default.extend-words]
# Mathematical/scientific terms
numer = "numer"
reparametrize = "reparametrize"
reparametrization = "reparametrization"
reparametrized = "reparametrized"
jacobian = "jacobian"
hessian = "hessian" 
eigenvalue = "eigenvalue"
eigenvector = "eigenvector"
discretization = "discretization"
linearization = "linearization"
parameterized = "parameterized"
discretized = "discretized"
vectorized = "vectorized"

# Julia-specific functions  
setp = "setp"
getp = "getp"
setu = "setu"
getu = "getu"
indexin = "indexin"
findfirst = "findfirst"
findlast = "findlast"
eachindex = "eachindex"

# Common variable patterns in Julia/SciML
ists = "ists"
ispcs = "ispcs"
osys = "osys"
rsys = "rsys"
usys = "usys"
fsys = "fsys"
eqs = "eqs"
rhs = "rhs"
lhs = "lhs"
ode = "ode"
pde = "pde"
sde = "sde"
dde = "dde"
bvp = "bvp"
ivp = "ivp"

# Common abbreviations
tol = "tol"
rtol = "rtol"
atol = "atol"
idx = "idx"
jdx = "jdx"
prev = "prev"
curr = "curr"
init = "init"
tmp = "tmp"
vec = "vec"
arr = "arr"
dt = "dt"
du = "du"
dx = "dx"
dy = "dy"
dz = "dz"

# Algorithm/type suffixes
alg = "alg"
prob = "prob"
sol = "sol"
cb = "cb"
opts = "opts"
args = "args"
kwargs = "kwargs"

# Scientific abbreviations
ND = "ND"
nd = "nd"
MTK = "MTK"
ODE = "ODE"
PDE = "PDE"
SDE = "SDE"

# StructuralIdentifiability-specific mathematical parameters
gam = "gam"  # Gamma parameter (recovery rate in epidemiological models)
gama = "gama"  # Gamma parameter variant
ba = "ba"  # Beta parameter (transmission rate)
bi = "bi"  # Beta_I parameter (infection transmission rate)
bw = "bw"  # Beta_W parameter (environmental transmission rate)
gir = "gir"  # Gamma_IR parameter (recovery rate)
mu = "mu"  # Mu parameter (death/birth rate)