# ------------------------------------------------------------------------------

function check_primality_zerodim(J::Array{QQMPolyRingElem, 1})
    J = Groebner.groebner(J)
    basis = Groebner.quotient_basis(J)
    dim = length(basis)
    S = Nemo.matrix_space(Nemo.QQ, dim, dim)
    matrices = []
    @debug "Dim is $dim"
    for v in gens(parent(first(J)))
        M = zero(S)
        for (i, vec) in enumerate(basis)
            image = Groebner.normalform(J, v * vec)
            for (j, base_vec) in enumerate(basis)
                M[i, j] = Nemo.QQ(coeff(image, base_vec))
            end
        end
        push!(matrices, M)
    end
    generic_multiplication = sum(Nemo.QQ(rand(1:100)) * M for M in matrices)
    @debug "Generic multiplication matrix computed"
    @debug "Trying reductions over primed first"
    NUM_PRIMES = 10
    p = 2^31 - 1
    for _ in 1:NUM_PRIMES
        @debug "Prime is $p"
        F = Nemo.GF(p)
        S_F = Nemo.matrix_space(F, dim, dim)
        generic_multiplication_modp = S_F([generic_multiplication[i, j] for i in 1:dim for j in 1:dim])
        R, t = Nemo.polynomial_ring(F, "t")
        chpoly = Nemo.charpoly(R, generic_multiplication_modp)
        @debug "Charpoly computed"
        if Nemo.is_irreducible(chpoly)
            return true
        end
        p = Primes.nextprime(p + 1)
    end

    @debug "No conclusion modulo primes, computing over Q"
    R, t = Nemo.polynomial_ring(Nemo.QQ, "t")
    chpoly = Nemo.charpoly(R, generic_multiplication)

    return Nemo.is_irreducible(chpoly)
end

#------------------------------------------------------------------------------
"""
    check_primality(polys::Dict{QQMPolyRingElem, QQMPolyRingElem}, extra_relations::Array{QQMPolyRingElem, 1})

The function checks if the ideal generated by the polynomials and saturated at
the leading coefficient with respect to the corresponding variables is prime
over rationals.

The `extra_relations` allows adding more polynomials to the generators (not affecting the saturation).
"""
function check_primality(
        polys::Dict{QQMPolyRingElem, QQMPolyRingElem},
        extra_relations::Array{QQMPolyRingElem, 1},
    )
    leaders = collect(keys(polys))
    ring = parent(leaders[1])

    Rspec, vspec = Nemo.polynomial_ring(Nemo.QQ, [var_to_str(l) for l in leaders])
    # Generic degree of each generator in its leader. Specializing the other
    # variables must preserve these degrees; the ideal is considered on the
    # open set where the leading coefficients (w.r.t. the leaders) do not
    # vanish, so a specialization that drops a degree corresponds to leaving
    # that set and would collapse the quotient ring, yielding a spurious result.
    leader_degrees = Dict(l => Nemo.degree(p, l) for (l, p) in polys)

    local zerodim_ideal
    attempts = 0
    while true
        attempts += 1
        eval_point = [v in keys(polys) ? v : ring(rand(1:100)) for v in gens(ring)]
        specialized = Dict(l => evaluate(polys[l], eval_point) for l in leaders)
        if all(Nemo.degree(specialized[l], l) == leader_degrees[l] for l in leaders)
            all_polys = vcat(
                [specialized[l] for l in leaders],
                [evaluate(p, eval_point) for p in extra_relations],
            )
            zerodim_ideal =
                collect(map(p -> parent_ring_change(p, Rspec), all_polys))
            break
        end
        if attempts >= 100
            error(
                "Failed to find a generic specialization for the primality check " *
                    "after $attempts attempts (the leading coefficients keep vanishing).",
            )
        end
    end

    return check_primality_zerodim(zerodim_ideal)
end

#------------------------------------------------------------------------------
"""
    check_primality(polys::Dict{QQMPolyRingElem, QQMPolyRingElem})

The function checks if the ideal generated by the polynomials and saturated at
the leading coefficient with respect to the corresponding variables is prime
over rationals.
"""
function check_primality(polys::Dict{QQMPolyRingElem, QQMPolyRingElem})
    return check_primality(polys, Array{QQMPolyRingElem, 1}())
end

# ------------------------------------------------------------------------------
