name: "Documentation"

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  docs:
    name: "Documentation"
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
